# Generated by Django 4.2.9 on 2025-04-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wfdash", "0011_remove_company_vendor_alter_company_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalStockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        help_text="Your unique internal part number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, help_text="Brand of the item", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description for the quote"),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default markup percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated or fixed selling price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default supplier (e.g., 'Internal Stock')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wfdash.suppliers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Stock Item",
                "verbose_name_plural": "Internal Stock Items",
                "ordering": ["part_number"],
            },
        ),
    ]
