# Generated by Django 4.2.9 on 2025-02-10 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfdash', '0003_companydetails'),
        ('orders', '0004_purchaseorder_notes_purchaseorder_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('received_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdash.suppliers')),
            ],
            options={
                'ordering': ['supplier', 'planned_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('partial_stock', 'Partial Stock'), ('quality_issue', 'Quality Issue'), ('wrong_item', 'Wrong Item'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collection_problems/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_list.collection')),
            ],
        ),
    ]
