# Generated by Django 4.2.9 on 2025-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('problem', 'Problem'), ('scheduled', 'Scheduled')], default='pending', max_length=20),
        ),
    ]
