# Generated by Django 4.2.9 on 2025-02-11 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0002_alter_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='planned_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
