# Generated by Django 4.2.9 on 2025-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0003_alter_collection_planned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('problem', 'Problem')], default='pending', max_length=20),
        ),
    ]
