# Generated by Django 4.2.9 on 2025-02-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0004_alter_collection_notes_alter_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
