# Generated by Django 4.2.9 on 2025-02-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_purchaseorder_options_and_more'),
        ('wfdash', '0007_alter_company_table'),
        ('driver_list', '0006_collection_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverListPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdash.suppliers')),
            ],
            options={
                'verbose_name': 'Driver List Pool',
                'verbose_name_plural': 'Driver List Pool',
            },
        ),
    ]
