# Generated by Django 4.2.9 on 2025-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0007_driverlistpool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlistpool',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverlistpool',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
