# Generated by Django 4.2.9 on 2025-02-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0008_alter_driverlistpool_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['supplier', 'planned_date'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
