# Generated by Django 4.2.9 on 2025-03-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_orders', '0003_stockorder_email_sent_to_stockorder_pdf_file_and_more'),
        ('orders', '0017_order_potential_quote_and_more'),
        ('driver_list', '0011_collection_description_collection_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlistpool',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_list_entries', to='stock_orders.stockorderitem'),
        ),
        migrations.AddField(
            model_name='driverlistpool',
            name='stock_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_list_entries', to='stock_orders.stockorder'),
        ),
        migrations.AlterField(
            model_name='driverlistpool',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_list_entries', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='driverlistpool',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_list_entries', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='driverlistpool',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_list_entries', to='orders.purchaseorder'),
        ),
    ]
