# Generated by Django 4.2.9 on 2025-03-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_orders', '0003_stockorder_email_sent_to_stockorder_pdf_file_and_more'),
        ('driver_list', '0012_driverlistpool_stock_item_driverlistpool_stock_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='stock_orders.stockorderitem'),
        ),
        migrations.AddField(
            model_name='collection',
            name='stock_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='stock_orders.stockorder'),
        ),
    ]
