# Generated by Django 4.2.9 on 2025-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalstockitem",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about this item (e.g., kit components, where to find items)",
            ),
        ),
    ]
