# Generated by Django 4.2.9 on 2025-04-22 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0010_company_vendor_alter_company_address_and_more'),
        ("internal_stock", "0002_internalstockitem_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Price list name (e.g., 'B&R 2025 Price List')",
                        max_length=200,
                    ),
                ),
                ("year", models.PositiveIntegerField(help_text="Year of price list")),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "default_markup",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Default markup percentage for items in this price list",
                        max_digits=5,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about this price list"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="wfdash.suppliers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Price List",
                "verbose_name_plural": "Supplier Price Lists",
                "ordering": ["-year", "supplier"],
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        blank=True, help_text="Supplier's part number", max_length=100
                    ),
                ),
                ("description", models.TextField(help_text="Item description")),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "markup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Markup percentage (leave blank to use price list default)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="internal_stock.supplierpricelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price List Item",
                "verbose_name_plural": "Price List Items",
                "ordering": ["description"],
            },
        ),
    ]
