# Generated by Django 4.2.9 on 2025-03-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0015_alter_quoteattachment_file'),
        ('orders', '0017_order_potential_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('quote', 'Quote Request'), ('order', 'Order')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_submission', to='orders.order')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_submission', to='quotes.quoterequest')),
            ],
        ),
    ]
