# Generated by Django 4.2.9 on 2025-03-30 17:21

import delivery_notes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_management', '0009_alter_stockitem_status'),
        ('wfdash', '0009_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0015_alter_quoteattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(default=delivery_notes.models.get_delivery_note_number, max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('delivered', 'Delivered'), ('signed', 'Signed'), ('converted', 'Converted to Quote'), ('ordered', 'Ordered')], default='draft', max_length=20)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=100)),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='delivery_signatures/')),
                ('digital_signature', models.TextField(blank=True)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='delivery_documents/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='delivery_notes/')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdash.company')),
                ('converted_to_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_delivery_note', to='quotes.quoterequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_notes.deliverynote')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='stock_management.stockitem')),
            ],
        ),
    ]
