# Generated by Django 4.2.9 on 2025-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0002_deliveryitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='signed_document',
            field=models.FileField(blank=True, help_text='Uploaded scanned copy of signed delivery note', null=True, upload_to='delivery_notes/signed_documents/'),
        ),
    ]
