# Generated by Django 4.2.9 on 2025-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_notes", "0003_deliverynote_customer_order_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryitem",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cost Price",
            ),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="markup",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Markup percentage (e.g., 30 for 30%)",
                max_digits=6,
                null=True,
                verbose_name="Markup %",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Selling Price",
            ),
        ),
    ]
