# Generated by Django 4.2.9 on 2025-04-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_notes", "0004_deliveryitem_cost_price_deliveryitem_markup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryitem",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="markup",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
