# Generated by Django 4.2.9 on 2025-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_notes", "0005_alter_deliveryitem_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("need_signature", "Need Signature"),
                    ("need_pricing", "Need Pricing"),
                    ("need_both", "Need Signature & Pricing"),
                    ("ready_to_invoice", "Ready to Invoice"),
                    ("completed", "Completed"),
                    ("delivered", "Delivered"),
                    ("signed", "Signed"),
                    ("converted", "Converted to Quote"),
                    ("ordered", "Ordered"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
