# Generated by Django 4.2.9 on 2025-04-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("delivery_notes", "0006_deliverynote_invoice_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="order_requested",
            field=models.BooleanField(
                default=False, help_text="Order number has been requested"
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="order_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_order_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="order_requested_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
