# Generated by Django 4.2.9 on 2025-04-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("delivery_notes", "0007_deliverynote_order_requested_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverynote",
            old_name="order_requested_date",
            new_name="last_order_requested_date",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="order_requested",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="order_requested_by",
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="last_order_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_requested_order_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="order_requests_count",
            field=models.IntegerField(
                default=0, help_text="Number of times an order has been requested"
            ),
        ),
    ]
