# Generated by Django 4.2.9 on 2025-02-09 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('rep', models.CharField(blank=True, max_length=255, null=True)),
                ('dateadded', models.DateTimeField(blank=True, null=True)),
                ('lastvisiteddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
                'db_table': 'wfdash_customers',
            },
        ),
        migrations.CreateModel(
            name='Driverlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('supplier', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, max_length=255, null=True)),
                ('completeddate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Driverlist',
                'verbose_name_plural': 'Driverlist',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Quoterequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('noteslink', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Quoterequest',
                'verbose_name_plural': 'Quoterequest',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField(blank=True, max_length=255, null=True)),
                ('closingtime', models.TextField(blank=True, max_length=255, null=True)),
                ('suppliername', models.TextField(blank=True, max_length=255, null=True)),
                ('suppliernumber', models.TextField(blank=True, max_length=255, null=True)),
                ('supplieraddress', models.TextField(blank=True, max_length=255, null=True)),
                ('supply_tags', models.CharField(blank=True, help_text='Enter tags separated by commas (e.g., bolts, nuts, paint)', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Suppliers',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
