# Generated by Django 4.2.9 on 2025-02-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False, 'verbose_name': 'Customers', 'verbose_name_plural': 'Customers'},
        ),
    ]
