# Generated by Django 4.2.9 on 2025-02-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0002_alter_customers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('vat_number', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
