# Generated by Django 4.2.9 on 2025-02-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0003_companydetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
    ]
