# Generated by Django 4.2.9 on 2025-02-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0004_alter_company_options_alter_customers_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='wfdash_company',
        ),
    ]
