# Generated by Django 4.2.9 on 2025-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0005_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False, 'verbose_name': 'Customers', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='name',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
