# Generated by Django 4.2.9 on 2025-02-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0006_alter_company_options_alter_companydetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
