# Generated by Django 4.2.9 on 2025-03-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0007_alter_company_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='phone',
        ),
    ]
