# Generated by Django 4.2.9 on 2025-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfdash", "0009_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="vendor",
            field=models.CharField(
                blank=True,
                help_text="Vendor number for mines or other organizations",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company",
            field=models.CharField(max_length=255),
        ),
    ]
