# Generated by Django 4.2.9 on 2025-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfdash", "0010_company_vendor_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
