# Generated by Django 4.2.9 on 2025-02-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_list', '0005_alter_collection_planned_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_companydetails_purchaseorder_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now_add=True)),
                ('received_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('invoiced', 'Invoiced'), ('ready_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='in_stock', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_list.collection')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
