# Generated by Django 4.2.9 on 2025-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='external_invoice_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='external_invoice_number',
            field=models.CharField(null=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='verified_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
    ]
