# Generated by Django 4.2.9 on 2025-02-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_stockitem_external_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='external_invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='external_invoice_number',
            field=models.CharField(max_length=50),
        ),
    ]
