# Generated by Django 4.2.9 on 2025-02-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_management', '0003_alter_stockitem_external_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='picked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
