# Generated by Django 4.2.9 on 2025-02-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0004_stockitem_picked_stockitem_picked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('invoiced', 'Invoiced'), ('picking', 'Picking in Progress'), ('picking_completed', 'Picking Completed'), ('ready_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='in_stock', max_length=20),
        ),
    ]
