# Generated by Django 4.2.9 on 2025-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0006_alter_stockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('office_stock', 'Office Stock'), ('invoiced', 'Invoiced'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='in_stock', max_length=20),
        ),
    ]
