# Generated by Django 4.2.9 on 2025-02-17 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_management', '0007_alter_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='loaded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('office_stock', 'Office Stock'), ('invoiced', 'Invoiced'), ('picked', 'Picked'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='in_stock', max_length=20),
        ),
    ]
