# Generated by Django 4.2.9 on 2025-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0008_stockitem_loaded_by_stockitem_loaded_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('picked', 'Picked'), ('loading', 'Loading'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='in_stock', max_length=20),
        ),
    ]
