# Generated by Django 4.2.9 on 2025-04-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_notes", "0003_deliverynote_customer_order_number_and_more"),
        ("stock_management", "0009_alter_stockitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="delivered_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="delivery_notes.deliverynote",
            ),
        ),
    ]
