# Generated by Django 4.2.9 on 2025-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0010_stockitem_delivered_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("picked", "Picked"),
                    ("loading", "Loading"),
                    ("ready_for_delivery", "Ready for Delivery"),
                    ("delivered", "Delivered"),
                ],
                default="verified",
                max_length=20,
            ),
        ),
    ]
