# Generated by Django 4.2.9 on 2025-04-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_orders_orde_status_c6dd84_idx_and_more"),
        ("stock_management", "0011_alter_stockitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.orderitem",
            ),
        ),
    ]
