# Generated by Django 4.2.9 on 2025-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='po_generated',
            field=models.BooleanField(default=False),
        ),
    ]
