# Generated by Django 4.2.9 on 2025-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_purchaseorder_notes_purchaseorder_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='po_generated',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('po_generated', 'PO Generated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('order_ready', 'Order Ready'), ('po_generated', 'PO Generated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
