# Generated by Django 4.2.9 on 2025-02-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0003_companydetails'),
        ('orders', '0007_order_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_number', 'company')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
