# Generated by Django 4.2.9 on 2025-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_companydetails_purchaseorder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
