# Generated by Django 4.2.9 on 2025-02-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
