# Generated by Django 4.2.9 on 2025-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_order_quantity_orderitem_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('po_generated', 'PO Generated'), ('driver_pool', 'In Driver Pool'), ('assigned', 'Assigned to Driver'), ('collected', 'Collected'), ('stock_verified', 'Stock Verified'), ('picking', 'Picking'), ('ready_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
