# Generated by Django 4.2.9 on 2025-03-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0012_remove_quoterequest_voice_note_voicenote"),
        ("orders", "0014_alter_purchaseorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_orders",
                to="quotes.quoterequest",
                verbose_name="Related Quote",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quote_match_confidence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quote_matching_attempted",
            field=models.BooleanField(default=False),
        ),
    ]
