# Generated by Django 4.2.9 on 2025-03-09 23:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0013_quoteitem_included_in_quote_quoteitem_quote_pdf_id"),
        ("orders", "0016_orderitem_po_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="potential_quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="potential_orders",
                to="quotes.quoterequest",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="potential_quote_confidence",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
