# Generated by Django 4.2.9 on 2025-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_orders_orde_status_c6dd84_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="po_description",
            field=models.TextField(
                blank=True, help_text="Description to use on the purchase order"
            ),
        ),
    ]
