# Generated by Django 4.2.9 on 2025-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
