# Generated by Django 4.2.9 on 2025-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoterequest_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='external_number',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='markup',
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quote_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quote_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
