# Generated by Django 4.2.9 on 2025-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_quoteitem_external_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='company_letterhead',
            field=models.CharField(choices=[('CNL', 'CNL'), ('ISHERWOOD', 'Isherwood')], default='CNL', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quote_pdfs/%Y/%m/'),
        ),
    ]
