# Generated by Django 4.2.9 on 2025-02-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quoterequest_company_letterhead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_quotes/%Y/%m/'),
        ),
    ]
