# Generated by Django 4.2.9 on 2025-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quoterequest_pdf_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='company_letterhead',
            field=models.CharField(choices=[('CNL', 'CNL Mining Supplies'), ('ISHERWOOD', 'Isherwood Engineering')], default='CNL', max_length=20),
        ),
    ]
