# Generated by Django 4.2.9 on 2025-02-24 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0010_quoteitem_markup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='quote_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='quote_voice_notes/%Y/%m/'),
        ),
    ]
