# Generated by Django 4.2.9 on 2025-02-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quoterequest_photo_quoterequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='voice_note',
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='quote_voice_notes/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='quotes.quoterequest')),
            ],
        ),
    ]
