# Generated by Django 4.2.9 on 2025-03-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0012_remove_quoterequest_voice_note_voicenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="included_in_quote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote_pdf_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
