# Generated by Django 4.2.9 on 2025-03-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quoteitem_included_in_quote_quoteitem_quote_pdf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='email_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_tracking_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="user",
            field=models.ForeignKey(
                null=True,  # Add this to make it temporarily nullable
                blank=True, # Add this too
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quotes',
                to="auth.user",
            ),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('claimed', 'Claimed'), ('processed', 'Processed'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('emailed', 'Emailed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicenote',
            name='audio_file',
            field=models.FileField(upload_to='voice_notes/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='EmailClickTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_url', models.URLField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_clicks', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
