# Generated by Django 4.2.9 on 2025-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_quoterequest_email_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteattachment',
            name='file',
            field=models.FileField(upload_to='quote_attachments/%Y/%m/%d/'),
        ),
    ]
