# Generated by Django 4.2.9 on 2025-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0015_alter_quoteattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("claimed", "Claimed"),
                    ("processed", "Processed"),
                    ("emailed", "Emailed"),
                    ("approval_pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("problem", "Problem Reported"),
                    ("complete", "Complete"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
