# Generated by Django 4.2.9 on 2025-03-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfdash', '0008_remove_companydetails_phone'),
        ('stock_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_orders', to='wfdash.suppliers'),
        ),
    ]
