# Generated by Django 4.2.9 on 2025-03-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_orders', '0002_alter_stockorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='email_sent_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='stock_orders/po_files/'),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
